Repository twopilogue/intervYou, pull requests merged in 2024-07, with the labels that each got.

#2 [FE] 스토리북 설치 및 컴포넌트 스토리 작성
  FE/.eslintrc.json
  FE/.gitignore
  FE/.storybook/main.ts
  FE/.storybook/preview.ts
  FE/next-env.d.ts
  FE/package-lock.json
  FE/package.json
  FE/pages/_app.tsx
  FE/pages/_components/button/Button.tsx
  FE/pages/_components/input/InputField.tsx
  FE/pages/_components/input/SearchField.tsx
  FE/pages/_components/input/TextArea.tsx
  FE/pages/global.css
  FE/pages/index.tsx
  FE/postcss.config.js
  FE/public/fonts/Pretendard-Bold.woff2
  FE/public/fonts/Pretendard-Regular.woff2
  FE/stories/Button.stories.ts
  FE/stories/Input.stories.ts
  FE/stories/Search.stories.ts
  FE/stories/TextArea.stories.ts
  FE/tailwind.config.js
  FE/tsconfig.json
Labels: design, frontend, test

#5 [FE] 네이버 소셜 로그인 연결
  FE/pages/_components/button/Button.tsx
  FE/pages/index.tsx
Labels: feature, frontend

#7 [BE] 네이버 소셜 로그인 구현
  BE/build.gradle
  BE/src/main/java/com/twopilogue/intervyou/common/dto/BaseResponse.java
  BE/src/main/java/com/twopilogue/intervyou/test/TestController.java
  BE/src/main/java/com/twopilogue/intervyou/user/constant/UserConstant.java
  BE/src/main/java/com/twopilogue/intervyou/user/controller/UserController.java
  BE/src/main/java/com/twopilogue/intervyou/user/dto/response/LoginResponse.java
  BE/src/main/java/com/twopilogue/intervyou/user/dto/response/naver/NaverIdTokenResponse.java
  BE/src/main/java/com/twopilogue/intervyou/user/dto/response/naver/NaverTokenResponse.java
  BE/src/main/java/com/twopilogue/intervyou/user/entity/User.java
  BE/src/main/java/com/twopilogue/intervyou/user/repository/UserRepository.java
  BE/src/main/java/com/twopilogue/intervyou/user/service/UserService.java
Labels: feature, backend, setting

#9 [FE] 헤더 컴포넌트 생성
  FE/.prettierrc
  FE/.storybook/main.ts
  FE/.storybook/preview.ts
  FE/next-env.d.ts
  FE/package-lock.json
  FE/package.json
  FE/pages/_app.tsx
  FE/pages/index.tsx
  FE/postcss.config.js
  FE/src/app/_components/button/Button.tsx
  FE/src/app/_components/header/Header.tsx
  FE/src/app/_components/input/InputField.tsx
  FE/src/app/_components/input/SearchField.tsx
  FE/src/app/_components/input/TextArea.tsx
  FE/src/app/layout.tsx
  FE/src/app/page.tsx
  FE/src/styles/globals.css
  FE/stories/Button.stories.ts
  FE/stories/Input.stories.ts
  FE/stories/Search.stories.ts
  FE/stories/TextArea.stories.ts
  FE/tailwind.config.js
  FE/tsconfig.json
Labels: design, frontend

#11 [BE] JWT 설정
  BE/build.gradle
  BE/src/main/java/com/twopilogue/intervyou/common/dto/BaseErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/common/dto/ErrorResponse.java
  BE/src/main/java/com/twopilogue/intervyou/config/CorsConfig.java
  BE/src/main/java/com/twopilogue/intervyou/config/SecurityConfig.java
  BE/src/main/java/com/twopilogue/intervyou/config/auth/PrincipalDetails.java
  BE/src/main/java/com/twopilogue/intervyou/config/auth/PrincipalDetailsService.java
  BE/src/main/java/com/twopilogue/intervyou/config/constant/ConfigConstant.java
  BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtAuthorizationFilter.java
  BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtExceptionHandler.java
  BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtProvider.java
  BE/src/main/java/com/twopilogue/intervyou/user/exception/UserErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/user/exception/UserException.java
  BE/src/main/java/com/twopilogue/intervyou/user/service/UserService.java
Labels: feature, backend, setting

#13 [공통] 소셜 로그인
  BE/build.gradle
  BE/src/main/java/com/twopilogue/intervyou/common/dto/BaseErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/common/dto/BaseResponse.java
  BE/src/main/java/com/twopilogue/intervyou/common/dto/ErrorResponse.java
  BE/src/main/java/com/twopilogue/intervyou/config/CorsConfig.java
  BE/src/main/java/com/twopilogue/intervyou/config/SecurityConfig.java
  BE/src/main/java/com/twopilogue/intervyou/config/auth/PrincipalDetails.java
  BE/src/main/java/com/twopilogue/intervyou/config/auth/PrincipalDetailsService.java
  BE/src/main/java/com/twopilogue/intervyou/config/constant/ConfigConstant.java
  BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtAuthorizationFilter.java
  BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtExceptionHandler.java
  BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtProvider.java
  BE/src/main/java/com/twopilogue/intervyou/test/TestController.java
  BE/src/main/java/com/twopilogue/intervyou/user/constant/UserConstant.java
  BE/src/main/java/com/twopilogue/intervyou/user/controller/UserController.java
  BE/src/main/java/com/twopilogue/intervyou/user/dto/response/LoginResponse.java
  BE/src/main/java/com/twopilogue/intervyou/user/dto/response/naver/NaverIdTokenResponse.java
  BE/src/main/java/com/twopilogue/intervyou/user/dto/response/naver/NaverTokenResponse.java
  BE/src/main/java/com/twopilogue/intervyou/user/entity/User.java
  BE/src/main/java/com/twopilogue/intervyou/user/exception/UserErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/user/exception/UserException.java
  BE/src/main/java/com/twopilogue/intervyou/user/repository/UserRepository.java
  BE/src/main/java/com/twopilogue/intervyou/user/service/UserService.java
  FE/.eslintrc.json
  FE/.gitignore
  FE/.prettierrc
  FE/.storybook/main.ts
  FE/.storybook/preview.ts
  FE/package-lock.json
  FE/package.json
  FE/pages/_app.tsx
  FE/pages/index.tsx
  FE/postcss.config.js
  FE/public/fonts/Pretendard-Bold.woff2
  FE/public/fonts/Pretendard-Regular.woff2
  FE/src/app/_components/button/Button.tsx
  FE/src/app/_components/header/Header.tsx
  FE/src/app/_components/input/InputField.tsx
  FE/src/app/_components/input/SearchField.tsx
  FE/src/app/_components/input/TextArea.tsx
  FE/src/app/layout.tsx
  FE/src/app/page.tsx
  FE/src/styles/globals.css
  FE/stories/Button.stories.ts
  FE/stories/Input.stories.ts
  FE/stories/Search.stories.ts
  FE/stories/TextArea.stories.ts
  FE/tailwind.config.js
  FE/tsconfig.json
Labels: feature, backend, frontend, setting

#15 [BE] Dockfile 수정
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  FE/Dockerfile
Labels: backend, frontend, setting

#16 [BE] Dockfile 수정
  FE/Dockerfile
Labels: frontend, setting

#17 [BE] Dockfile 수정
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: backend, frontend, setting

#18 [BE] 회원탈퇴 API 구현
  BE/src/main/java/com/twopilogue/intervyou/config/auth/PrincipalDetailsService.java
  BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtAuthorizationFilter.java
  BE/src/main/java/com/twopilogue/intervyou/user/constant/UserConstant.java
  BE/src/main/java/com/twopilogue/intervyou/user/controller/UserController.java
  BE/src/main/java/com/twopilogue/intervyou/user/entity/User.java
  BE/src/main/java/com/twopilogue/intervyou/user/exception/UserErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/user/repository/UserRepository.java
  BE/src/main/java/com/twopilogue/intervyou/user/service/UserService.java
Labels: feature, backend

#21 [BE] 사용자 닉네임 추가
  BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtProvider.java
  BE/src/main/java/com/twopilogue/intervyou/user/constant/UserConstant.java
  BE/src/main/java/com/twopilogue/intervyou/user/dto/response/LoginResponse.java
  BE/src/main/java/com/twopilogue/intervyou/user/entity/User.java
  BE/src/main/java/com/twopilogue/intervyou/user/repository/UserRepository.java
  BE/src/main/java/com/twopilogue/intervyou/user/service/UserService.java
Labels: feature, backend

#22 [BE] 게시글 등록 API 구현
  BE/build.gradle
  BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
  BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/request/WritePostRequest.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/WritePostResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/entity/Community.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend, setting

#24 [BE] 게시글 수정 API 구현
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  BE/src/main/java/com/twopilogue/intervyou/common/BaseErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/common/BaseResponse.java
  BE/src/main/java/com/twopilogue/intervyou/common/ErrorResponse.java
  BE/src/main/java/com/twopilogue/intervyou/common/GlobalExceptionHandler.java
  BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
  BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/request/ModifyPostRequest.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/ModifyPostResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/entity/Community.java
  BE/src/main/java/com/twopilogue/intervyou/community/exception/CommunityErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/community/exception/CommunityException.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
  BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtExceptionHandler.java
  BE/src/main/java/com/twopilogue/intervyou/user/controller/UserController.java
  BE/src/main/java/com/twopilogue/intervyou/user/exception/UserErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/user/exception/UserException.java
Labels: feature, backend

#26 [BE] 댓글 등록 API 구현
  BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
  BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/request/WriteCommentRequest.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/WriteCommentResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/entity/Comment.java
  BE/src/main/java/com/twopilogue/intervyou/community/exception/CommunityErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommentRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend

#31 [BE] actions 동작 브랜치 변경
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: backend, frontend, setting

#32 [BE] 댓글 삭제 API 구현
  BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
  BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
  BE/src/main/java/com/twopilogue/intervyou/community/entity/Comment.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend

#34 [FE] 면접 시작 및 진행 페이지 컴포넌트 생성
  FE/src/app/_components/button/Button.tsx
  FE/src/app/_components/header/Header.tsx
  FE/src/app/_components/input/InputField.tsx
  FE/src/app/_components/input/TextArea.tsx
  FE/src/app/content/_components/Bubble/index.tsx
  FE/src/app/content/_components/Header/index.tsx
  FE/src/app/content/page.tsx
  FE/src/app/create/_components/CheckBox/index.tsx
  FE/src/app/create/_components/Radio/index.tsx
  FE/src/app/create/page.tsx
  FE/src/app/layout.tsx
  FE/stories/Button.stories.ts
  FE/tailwind.config.js
Labels: design, frontend

#36 [FE] 면접 목록 컴포넌트 생성
  FE/package-lock.json
  FE/package.json
  FE/src/app/_components/header/Header.tsx
  FE/src/app/chat/_components/Bubble/index.tsx
  FE/src/app/chat/_components/Header/index.tsx
  FE/src/app/chat/page.tsx
  FE/src/app/create/page.tsx
  FE/src/app/layout.tsx
  FE/src/app/list/[chatId]/page.tsx
  FE/src/app/list/_components/ListFrame.tsx
  FE/src/app/list/_components/ListItem.tsx
  FE/src/app/list/layout.tsx
  FE/src/app/list/page.tsx
  FE/src/app/page.tsx
Labels: design, frontend

#38 [FE] 커뮤니티 목록 컴포넌트 생성
  FE/src/app/_components/header/Header.tsx
  FE/src/app/_components/input/SearchField.tsx
  FE/src/app/board/BoardFrame.tsx
  FE/src/app/board/BoardItem.tsx
  FE/src/app/board/Pagination.tsx
  FE/src/app/board/page.tsx
  FE/src/app/chat/_components/Header/index.tsx
Labels: design, frontend

#40 [BE] 게시글 삭제 API 구현
  BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
  BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommentRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend

#42 [FE] 커뮤니티 게시글 작성 컴포넌트 생성
  FE/src/app/board/create/TextArea.tsx
  FE/src/app/board/create/page.tsx
  FE/src/app/board/page.tsx
Labels: design, frontend

#44 [BE] 게시글 조회 API 구현
  BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
  BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/CommentResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/PostResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/exception/CommunityErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommentRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend

#46 [BE] 게시글 작성, 댓글 작성 응답 dto 변경
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/ModifyPostResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/WriteCommentResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/WritePostResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend

#48 [BE] 게시글 목록 조회 API 구현
  BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
  BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/PostListDtoResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/PostListResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommentRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend

#50 [BE] 내가 등록한 게시글 목록 조회 API 구현
  BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend

#52 [BE] 내가 등록한 댓글 목록 조회
  BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
  BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/CommentListDtoResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/dto/response/CommentListResponse.java
  BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommentRepository.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend

#54 [BE] 사용하지 않는 엔티티 필드 삭제
  BE/src/main/java/com/twopilogue/intervyou/community/entity/Comment.java
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
Labels: feature, backend

#56 [FE] 커뮤니티 게시글 조회 컴포넌트 생성
  FE/src/app/board/create/page.tsx
  FE/src/app/board/detail/CommentItem.tsx
  FE/src/app/board/detail/[pageId]/page.tsx
Labels: design, frontend

#58 [FE] 마이페이지 컴포넌트 생성
  FE/src/app/board/detail/[pageId]/page.tsx
  FE/src/app/board/page.tsx
  FE/src/app/chat/page.tsx
  FE/src/app/mypage/details/comment/CommentItem.tsx
  FE/src/app/mypage/details/comment/page.tsx
  FE/src/app/mypage/details/layout.tsx
  FE/src/app/mypage/details/post/PostItem.tsx
  FE/src/app/mypage/details/post/page.tsx
  FE/src/app/mypage/page.tsx
Labels: design, frontend

#59 [공통] 커뮤니티 및 마이페이지 관련 서비스 배포
  FE/src/app/board/create/page.tsx
  FE/src/app/board/detail/CommentItem.tsx
  FE/src/app/board/detail/[pageId]/page.tsx
  FE/src/app/board/page.tsx
  FE/src/app/chat/page.tsx
  FE/src/app/mypage/details/comment/CommentItem.tsx
  FE/src/app/mypage/details/comment/page.tsx
  FE/src/app/mypage/details/layout.tsx
  FE/src/app/mypage/details/post/PostItem.tsx
  FE/src/app/mypage/details/post/page.tsx
  FE/src/app/mypage/page.tsx
Labels: feature, frontend, setting

#64 [BE] CORS 에러 수정
  BE/src/main/java/com/twopilogue/intervyou/config/CorsConfig.java
Labels: backend, fix

#65 [BE] CORS 에러 수정
  BE/src/main/java/com/twopilogue/intervyou/config/CorsConfig.java
Labels: backend, fix

#66 [FE] 소셜 로그인 API 테스트
  FE/next.config.js
  FE/src/app/_components/header/Header.tsx
  FE/src/app/login/page.tsx
Labels: feature, test

#67 [FE] 소셜 로그인 관련 서비스 배포
  FE/next.config.js
  FE/src/app/_components/header/Header.tsx
  FE/src/app/login/page.tsx
Labels: frontend, setting

#68 [FE] 빌드 에러 수정
  FE/src/app/login/Login.tsx
  FE/src/app/login/page.tsx
Labels: fix, frontend

#69 [FE] 빌드 에러 수정
  FE/src/app/login/Login.tsx
  FE/src/app/login/page.tsx
Labels: fix, frontend, setting

#70 [BE] 채팅방 생성 API 구현
  BE/src/main/java/com/twopilogue/intervyou/common/GlobalExceptionHandler.java
  BE/src/main/java/com/twopilogue/intervyou/config/OpenAiConfig.java
  BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
  BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/chatgpt/ChatGPTRequest.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/chatgpt/ChatGPTResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/chatgpt/Message.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/request/StartInterviewRequest.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/StartInterviewResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/entity/Interview.java
  BE/src/main/java/com/twopilogue/intervyou/interview/entity/InterviewSequence.java
  BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewException.java
  BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewRepository.java
  BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewSequenceRepository.java
  BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java
Labels: feature, backend, setting

#72 [BE] 진행중인 면접 체크 API 구현
  BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
  BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/CheckOngoingInterviewResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewRepository.java
  BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java
Labels: feature, backend

#76 [BE] 면접 종료 API 구현
  BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
  BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
  BE/src/main/java/com/twopilogue/intervyou/interview/entity/Interview.java
  BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java
Labels: feature, backend

#77 [FE] 소셜 로그인 API 연결
  FE/package-lock.json
  FE/package.json
  FE/src/app/_components/header/Header.tsx
  FE/src/app/login/Redirect.tsx
  FE/src/app/login/page.tsx
  FE/src/app/mypage/page.tsx
  FE/src/slices/auth.slice.ts
Labels: feature, frontend

#79 [FE] 커뮤니티 게시글 목록 조회 API 연결
  FE/next.config.js
  FE/src/app/_components/header/Header.tsx
  FE/src/app/board/BoardFrame.tsx
  FE/src/app/board/BoardItem.tsx
  FE/src/app/board/Pagination.tsx
  FE/src/app/board/page.tsx
  FE/src/app/chat/_components/Header/index.tsx
  FE/src/app/community/CommunityFrame.tsx
  FE/src/app/community/CommunityItem.tsx
  FE/src/app/community/Pagination.tsx
  FE/src/app/community/[page]/page.tsx
  FE/src/app/community/create/TextArea.tsx
  FE/src/app/community/create/page.tsx
  FE/src/app/community/detail/CommentItem.tsx
  FE/src/app/community/detail/[pageId]/page.tsx
  FE/src/app/layout.tsx
  FE/src/hooks/usePagination.tsx
  FE/src/interfaces/community.interface.ts
  FE/src/slices/auth.slice.ts
Labels: feature, frontend, issue

#82 [FE] 커뮤니티 게시글 관련 API 연결
  FE/src/app/community/CommunityItem.tsx
  FE/src/app/community/create/CommunityCreate.tsx
  FE/src/app/community/create/page.tsx
  FE/src/app/community/detail/CommentInput.tsx
  FE/src/app/community/detail/CommentItem.tsx
  FE/src/app/community/detail/[pageId]/page.tsx
  FE/src/app/community/edit/[communityId]/page.tsx
  FE/src/interfaces/community.interface.ts
Labels: feature, frontend

#84 [BE] 이전 면접 기록 삭제 API 구현
  BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
  BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/request/StartInterviewRequest.java
  BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewRepository.java
  BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewSequenceRepository.java
  BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java
Labels: feature, backend

#86 [BE] 이전 면접 기록 목록 조회 API 구현
  BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
  BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewRecordListResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewRecordResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewRepository.java
  BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java
Labels: feature, backend

#88 [BE] 면접 기록 조회 API 구현
  BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
  BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java
Labels: feature, backend

#91 [FE] 알림창 컴포넌트 생성
  FE/src/app/_components/header/Header.tsx
  FE/src/app/_components/modal/alert/AlertItem.tsx
  FE/src/app/_components/modal/alert/ModalAlert.tsx
  FE/src/app/_components/modal/menu/ModalMenu.tsx
  FE/src/app/mypage/page.tsx
Labels: design, frontend

#93 [FE] 404 페이지 컴포넌트 생성
  FE/src/app/not-found.tsx
Labels: feature, frontend

#95 [BE] yml 파일 수정
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: backend, setting

#96 [공통] 서비스 배포
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  BE/src/main/java/com/twopilogue/intervyou/common/GlobalExceptionHandler.java
  BE/src/main/java/com/twopilogue/intervyou/config/OpenAiConfig.java
  BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
  BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/chatgpt/ChatGPTRequest.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/chatgpt/ChatGPTResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/chatgpt/Message.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/request/StartInterviewRequest.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/CheckOngoingInterviewResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewContentResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewRecordListResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewRecordResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/StartInterviewResponse.java
  BE/src/main/java/com/twopilogue/intervyou/interview/entity/Interview.java
  BE/src/main/java/com/twopilogue/intervyou/interview/entity/InterviewSequence.java
  BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewErrorResult.java
  BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewException.java
  BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewRepository.java
  BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewSequenceRepository.java
  BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java
  FE/next.config.js
  FE/package-lock.json
  FE/package.json
  FE/src/app/_components/header/Header.tsx
  FE/src/app/_components/modal/alert/AlertItem.tsx
  FE/src/app/_components/modal/alert/ModalAlert.tsx
  FE/src/app/_components/modal/menu/ModalMenu.tsx
  FE/src/app/board/BoardFrame.tsx
  FE/src/app/board/BoardItem.tsx
  FE/src/app/board/Pagination.tsx
  FE/src/app/board/create/page.tsx
  FE/src/app/board/detail/CommentItem.tsx
  FE/src/app/board/detail/[pageId]/page.tsx
  FE/src/app/board/page.tsx
  FE/src/app/chat/_components/Header/index.tsx
  FE/src/app/community/CommunityFrame.tsx
  FE/src/app/community/CommunityItem.tsx
  FE/src/app/community/Pagination.tsx
  FE/src/app/community/[page]/page.tsx
  FE/src/app/community/create/CommunityCreate.tsx
  FE/src/app/community/create/TextArea.tsx
  FE/src/app/community/create/page.tsx
  FE/src/app/community/detail/CommentInput.tsx
  FE/src/app/community/detail/CommentItem.tsx
  FE/src/app/community/detail/[pageId]/page.tsx
  FE/src/app/community/edit/[communityId]/page.tsx
  FE/src/app/layout.tsx
  FE/src/app/login/Redirect.tsx
  FE/src/app/login/page.tsx
  FE/src/app/mypage/page.tsx
  FE/src/app/not-found.tsx
  FE/src/hooks/usePagination.tsx
  FE/src/interfaces/community.interface.ts
  FE/src/slices/auth.slice.ts
Labels: feature, backend, frontend, setting

#98 [BE] mysql 의존성 추가
  BE/build.gradle
Labels: backend, setting

#99 [공통] 서비스 배포
  BE/build.gradle
Labels: backend, setting

#102 [BE] yml 파일 수정
  .github/workflows/backend.yml
Labels: backend, setting

#103 [FE] 프론트엔드 배포 설정
  .github/workflows/deploy.yml
  FE/build.sh
Labels: frontend, setting

#105 [BE] yml 파일 수정
  .github/workflows/frontend.yml
  BE/build.gradle
Labels: backend, setting

#107 [FE] 프론트엔드 배포 파일 수정
  .github/workflows/deploy.yml
Labels: feature, setting

#108 [FE] 프론트엔드 배포 파일 수정
  .github/workflows/deploy.yml
Labels: frontend, setting

#109 [BE] yml 파일 수정
  .github/workflows/backend.yml
Labels: backend, setting

#110 [FE] 확인 모달 컴포넌트 생성
  FE/src/app/_components/button/Button.tsx
  FE/src/app/_components/modal/confirm/ModalConfirm.tsx
  FE/src/app/community/create/CommunityCreate.tsx
  FE/tailwind.config.js
Labels: feature, frontend

#111 [FE] 커뮤니티 댓글 API 연결
  FE/src/app/community/[page]/page.tsx
  FE/src/app/community/detail/CommentInput.tsx
  FE/src/app/community/detail/CommentItem.tsx
  FE/src/app/community/detail/[pageId]/page.tsx
Labels: feature, frontend

#113 [FE] 커뮤니티 게시글 및 댓글 모달 연결
  FE/src/app/community/create/CommunityCreate.tsx
  FE/src/app/community/detail/CommentItem.tsx
  FE/src/app/community/detail/[pageId]/page.tsx
Labels: feature, frontend

#115 [FE] 마이페이지 내가 작성한 게시글, 댓글 조회 API 연결
  FE/src/app/_components/pagination/Pagination.tsx
  FE/src/app/community/[page]/page.tsx
  FE/src/app/community/detail/CommentInput.tsx
  FE/src/app/mypage/detail/comment/MyCommentItem.tsx
  FE/src/app/mypage/detail/comment/[page]/page.tsx
  FE/src/app/mypage/detail/layout.tsx
  FE/src/app/mypage/detail/post/MyCommunityItem.tsx
  FE/src/app/mypage/detail/post/[page]/page.tsx
  FE/src/app/mypage/details/comment/CommentItem.tsx
  FE/src/app/mypage/details/comment/page.tsx
  FE/src/app/mypage/details/post/PostItem.tsx
  FE/src/app/mypage/details/post/page.tsx
  FE/src/app/mypage/page.tsx
Labels: feature, frontend

#118 [FE] 프론트엔드 배포 환경 제거
  .github/workflows/deploy.yml
  FE/build.sh
Labels: frontend, setting

#120 [BE] yml 파일 수정
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: setting

#121 [BE] yml 파일 수정
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: setting

#123 [BE] 댓글 등록 시 실시간 알림 전송
  BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java
  BE/src/main/java/com/twopilogue/intervyou/notification/dto/response/NotificationResponse.java
  BE/src/main/java/com/twopilogue/intervyou/notification/entity/Notification.java
  BE/src/main/java/com/twopilogue/intervyou/notification/repository/NotificationRepository.java
  BE/src/main/java/com/twopilogue/intervyou/notification/service/NotificationService.java
  BE/src/main/java/com/twopilogue/intervyou/notification/service/WebSocketService.java
  BE/src/main/java/com/twopilogue/intervyou/user/repository/UserRepository.java
Labels: feature, backend

#125 [BE] 알림 목록 조회 API 구현
  BE/src/main/java/com/twopilogue/intervyou/notification/constant/NotificationConstant.java
  BE/src/main/java/com/twopilogue/intervyou/notification/controller/NotificationController.java
  BE/src/main/java/com/twopilogue/intervyou/notification/dto/response/NotificationListDtoResponse.java
  BE/src/main/java/com/twopilogue/intervyou/notification/dto/response/NotificationListResponse.java
  BE/src/main/java/com/twopilogue/intervyou/notification/repository/NotificationRepository.java
  BE/src/main/java/com/twopilogue/intervyou/notification/service/NotificationService.java
Labels: feature, backend

#126 [FE] zustand 에러 수정
  FE/src/app/login/Redirect.tsx
  FE/src/slices/auth.slice.ts
Labels: fix, frontend
